INSERT INTO taskdb.ITEM (ID,NAME,DESCRIPTION,PRICE,MODEL)VALUES('MOUSE031','MOUSE 300 DPI','MOUSE GENIUS 300 DPI',150.00,'GAMMER-B');
INSERT INTO taskdb.ITEM (ID,NAME,DESCRIPTION,PRICE,MODEL)VALUES('MOUSE040','MOUSE 300 DPI ROJO','MOUSE GENIUS 300 DPI ROJO',160.00,'GAMMER-C');
INSERT INTO taskdb.ITEM (ID,NAME,DESCRIPTION,PRICE,MODEL)VALUES('KEYBOAR01','KEYBOARD-BLACK','KEYBOARD BLACK',250.00,'KEYBOARD01');
INSERT INTO taskdb.ITEM (ID,NAME,DESCRIPTION,PRICE,MODEL)VALUES('MOUSE_PAD','MOUSE PAD ERGONOMIC','MOUSE PAD ERGONOMIC FLEXIBLE',60.00,'MOPUSEPAD3');
